<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>resultDataForSuburb</name>
   <tag></tag>
   <elementGuidId>0764279c-9cc3-48ea-ada4-78661cf9b15d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@class = 'location__title']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>location__title</value>
      <webElementGuid>c3a39ac5-c2c3-4014-90b2-276d79ee350c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2cfdeb53-200d-4d08-8447-b60c7331bc9a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
